### ISSUE TITLE
Dataset used in Paper Link is not working (Google Drive Link)

### ISSUE THREAD

**Issue by riazspace** [wiseodd/cnn-levelset#1]
Thank you for sharing your paper code with us. Unfortunately, I am unable to download the dataset from provided URL (https://drive.google.com/open?id=0BzFf_WMmDYN8dUdYZE9iMEZXS0k). Can you please help me out regarding this issue.

**Comment by wiseodd** [comment]
Hi, the dataset in that link is just an arbitrary subset of PASCAL VOC 2012 dataset, which is publicly available.
