### ISSUE TITLE
Data set link corruption

### ISSUE THREAD

**Issue by Dan7h3x** [wiseodd/cnn-levelset#2]
Hi there. I am very appreciated with your works. 
With apologies, the google drive link for test dataset is not working and i need to reach that, please inform me with solution. Thank you.

**Comment by wiseodd** [comment]
Hi, indeed I've lost the dataset (it's been 7 years 😬). I'm not even sure if the code can still be run since so much has changed in deep learning frameworks.

You can either use this repo as a reference when implementing yourself or find a newer paper that comes with newer code.
