### ISSUE TITLE
”data“ file missing content

### ISSUE THREAD

**Issue by Leee-l** [wiseodd/cnn-levelset#3]
Hi. I really appreciate your work.
I have downloaded your code, but I found that some important subfiles are missing under the data file, if you can provide them, I would appreciate it.
Thank you.

**Comment by wiseodd** [comment]
Hi, indeed I've lost the dataset (it's been 7 years 😬). I'm not even sure if the code can still be run since so much has changed in deep learning frameworks.

You can either use this repo as a reference when implementing yourself or find a newer paper that comes with newer code.
